### ISSUE TITLE
How else do I contact you

### ISSUE THREAD

**Issue by OxSon** [Anode194/configs#1]
Hey Jo!

It's Alec. We took 2420 together with Margret @ slcc. 

I've been wanting to reach out and pick your brain about some keeb stuff but haven't figured out who you are on discord in order to do so. If you're cool with chatting, send me your phone number/email/discord/your_preferred_contact_method !

**Comment by Anode194** [comment]
Oh hey! yeah discords cool Anode7[Jo]#9073
